export const bundeslandBP = {
    a: "bayern",
    b: "niedersachsen",
    c: "baden-Württemberg",
    d: "nordrhein-Westfalen",
    e: "brandenburg",
    f: "mecklenburg-Vorpommern",
    g: "hessen",
    h: "sachsen-Anhalt",
    i: "rheinland-Pfalz",
    j: "sachsen",
    k: "thüringen",
    l: "schleswig-Holstein",
    m: "saarland",
    n: "berlin",
    o: "hamburg",
    p: "bremen",
}
export const themenschwerpunktBP = {
    a: "Bildung & Professionalisierung",
    b: "Kultur & Kunst",
    c: "Gesundheit & Soziales",
    d: "Recht",
    e: "Politik & Advocacy",
    f: "Community-Building",
    g: "Beratung",
    h: "Wissenschaft",
    i: "Sprachen & Übersetzungsarbeit",
    j: "Kinder & Jugend",
    k: "Sport & Freizeit",
    l: "Religion",
    m: "Flucht & Migration",
}

export const artderorganisationBP = {
    a: "Verein",
    b: "Initiative",
    c: "NGO (Nichtregierungsorganisation)",
    d: "Projekt",
    e: "Bildungseinrichtung",
    f: "Kultureinrichtung",
    g: "Verbund/Verband",
    h: "Kollektiv",
    i: "Weitere",
}

export const zielgruppeBP = {
    a: "Afrikanische/Schwarze Kinder & Jugendliche",
    b: "Afrikanische/Schwarze Frauen",
    c: "Afrikanische/Schwarze Männer",
    d: "Afrikanische/Schwarze FLINTA(*)",
    e: "Afrikanische/Schwarze LSBTQIA+",
    f: "Afrikanische/Schwarze Geflüchtete & Migrant*innen",
    g: "Afrikanische/Schwarze Studierenden",
    h: "Afrikanische/Schwarze Auszubildende",
    i: "Afrikanische/Schwarze Menschen mit Behinderungen/chronischen Erkrankungen",
    j: "Afrikanische/Schwarze Menschen höheren Alters und Senior*innen",
    k: "Eltern/Bezugspersonen/Pflegeverantwortliche Afrikanischer/Schwarzer Kinder",
    l: "Pflegeverantwortliche/Angehörige Afrikanischer/Schwarzer Personen",
    m: "Afrikanische/Schwarze Fachkräfte und Freischaffende",
    o: "Familien mit Afrikanischen/ Schwarzen Mitgliedern",
    p: "Weitere",
}

// Do you need this code?🤔
export const onlineresourcenBP = {
    web: "Website vorhanden",
    social: "Social-Media-Präsenz (z. B. Facebook, Twitter, etc.)",
}

export const sprachunterstutzungBP = {
    a: "Afrikaans",
    b: "Albanisch",
    c: "Amharisch",
    d: "Arabisch",
    e: "Armenisch",
    f: "Aserbaidschanisch",
    g: "Baskisch",
    h: "Weißrussisch (Belarussisch)",
    i: "Bengalisch",
    j: "Bosnisch",
    k: "Bulgarisch",
    l: "Birmanisch",
    m: "Katalanisch",
    n: "Cebuano",
    o: "Chinesisch",
    p: "Kroatisch",
    q: "Tschechisch",
    r: "Dänisch",
    s: "Niederländisch",
    t: "Englisch",
    u: "Esperanto",
    v: "Estnisch",
    w: "Finnisch",
    x: "Französisch",
    y: "Galicisch",
    z: "Georgisch",
    aa: "Deutsch",
    bb: "Griechisch",
    cc: "Gujarati",
    dd: "Haitianisch-Kreolisch",
    ee: "Hausa",
    ff: "Hebräisch",
    gg: "Hindi",
    hh: "Ungarisch",
    ii: "Isländisch",
    jj: "Igbo",
    kk: "Indonesisch",
    ll: "Irisch",
    mm: "Italienisch",
    nn: "Japanisch",
    oo: "Javanisch",
    pp: "Kannada",
    qq: "Kasachisch",
    rr: "Khmer",
    ss: "Kinyarwanda",
    tt: "Koreanisch",
    uu: "Kurdisch",
    vv: "Kirgisisch",
    ww: "Laotisch",
    xx: "Lettisch",
    yy: "Litauisch",
    zz: "Luxemburgisch",
    aaa: "Mazedonisch",
    bbb: "Madagassisch",
    ccc: "Malaiisch",
    ddd: "Malayalam",
    eee: "Maltesisch",
    fff: "Maori",
    ggg: "Marathi",
    hhh: "Mongolisch",
    iii: "Nepalesisch",
    jjj: "Norwegisch",
    kkk: "Odia",
    lll: "Paschtunisch",
    mmm: "Persisch",
    nnn: "Polnisch",
    ooo: "Portugiesisch",
    ppp: "Panjabi (Punjabi)",
    qqq: "Rumänisch",
    rrr: "Russisch",
    sss: "Samoanisch",
    ttt: "Schottisch-Gälisch",
    uuu: "Serbisch",
    vvv: "Shona",
    www: "Sindhi",
    xxx: "Singhalesisch",
    yyy: "Slowakisch",
    zzz: "Slowenisch",
    aaaa: "Somali",
    bbbb: "Spanisch",
    cccc: "Sundanesisch",
    dddd: "Suaheli",
    eeee: "Schwedisch",
    ffff: "Tagalog",
    gggg: "Tadschikisch",
    hhhh: "Tamil",
    iiii: "Tatarisch",
    jjjj: "Telugu",
    kkkk: "Thailändisch",
    llll: "Tigrinya",
    mmmm: "Tongaisch",
    nnnn: "Türkisch",
    oooo: "Turkmenisch",
    pppp: "Ukrainisch",
    qqqq: "Urdu",
    rrrr: "Uigurisch",
    ssss: "Usbekisch",
    tttt: "Vietnamesisch",
    uuuu: "Walisisch",
    vvvv: "Xhosa",
    wwww: "Jiddisch",
    xxxx: "Yoruba",
    yyyy: "Zulu",
}

export const angeboteBP = {
    a: "Workshops & Seminare",
    b: "Veranstaltungen & Events",
    c: "Beratungsdienste",
    d: "Forschung",
    e: "Publikationen & (Online-)Ressourcen/Materialien",
    f: "Bibliothek/Archiv",
    g: "Freizeitangebote",
    h: "Nachhilfe",
    i: "Sprachunterricht",
    j: "Übersetzungen",
    k: "Dolmetschung",
    l: "Betreuung/Pflegedienste",
    m: "Kinder- & Jugendbetreuung",
    o: "Coaching/Supervision",
    p: "Aus- & Weiterbildungen",
    q: "Inputs & Vorträge",
    r: "Networking",
    s: "Weitere",
}
export const socialMediaBP = {
    a: "Facebook",
    b: "YouTube",
    c: "WhatsApp",
    d: "Instagram",
    e: "LinkedIn",
    f: "Telegram",
    g: "X(Twitter)",
}