export const RANDOM_FONT_LIST = [
  "font-aktura",
  "font-alfaSlabOne",
  "font-bespokeStencilItalic",
  "font-britney",
  "font-courier",
  "font-courierBold",
  "font-panchang",
  "font-sharpie",
  "font-telma",
  "font-theFutureMono",
  "font-jetBrainsMonoMedium",
  "font-jetBrainsMonoLight",
  "font-jetBrainsMonoExtraBold",
  "font-pramukhRoundedExtraboldItalic",
  "font-theFutureMono",
  "font-theFutureMonoBold",
];

export const RANDOM_FONT_LIST_SIZE = {
  "font-aktura": 30,
  "font-alfaSlabOne": 25,
  "font-bespokeStencilItalic": 30,
  "font-britney": 30,
  "font-courier": 30,
  "font-courierBold": 30,
  "font-panchang": 30,
  "font-sharpie": 30,
  "font-telma": 30,
  "font-theFutureMono": 30,
  "font-jetBrainsMonoMedium": 30,
  "font-jetBrainsMonoLight": 30,
  "font-jetBrainsMonoExtraBold": 30,
  "font-pramukhRoundedExtraboldItalic": 30,
  "font-theFutureMono": 30,
  "font-theFutureMonoBold": 30,
};
