export const RANDOM_FONT_LIST = [
  "font-aktura",
  "font-alfaSlabOne",
  "font-bespokeStencilItalic",
  "font-britney",
  "font-courier",
  "font-courierBold",
  "font-panchang",
  "font-sharpie",
  "font-telma",
  "font-theFutureMono",
  "font-jetBrainsMonoMedium",
  "font-jetBrainsMonoLight",
  "font-jetBrainsMonoExtraBold",
  "font-pramukhRoundedExtraboldItalic",
  "font-theFutureMono",
  "font-theFutureMonoBold",
];

export const RANDOM_FONT_LIST_SIZE = {
  "font-aktura": 40,
  "font-alfaSlabOne": 40,
  "font-bespokeStencilItalic": 40,
  "font-britney": 40,
  "font-courier": 40,
  "font-courierBold": 40,
  "font-panchang": 30,
  "font-sharpie": 40,
  "font-telma": 40,
  "font-theFutureMono": 40,
  "font-jetBrainsMonoMedium": 40,
  "font-jetBrainsMonoLight": 40,
  "font-jetBrainsMonoExtraBold": 40,
  "font-pramukhRoundedExtraboldItalic": 40,
  "font-theFutureMono": 40,
  "font-theFutureMonoBold": 40,
};
